name: ci

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, macos-latest, windows-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ../src
      shell: bash
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: cd build && ctest -C Release
      shell: bash
